# Default values for api-demo.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
serviceType: ClusterIP
servicePort: 80
containerPort: 8080
component: "hellojava"
replicas: 1
image: "cloudiqreg.azurecr.io/kubernetes/hellojava"
imageTag: "latest"
imagePullPolicy: "Always"
cpu: "10m"
memory: "128Mi"
# Ingress settings
ingress:
  enabled: true
  hostname: hellojava.aks.azurecr.io
  annotations:
     kubernetes.io/ingress.class: traefik
     kubernetes.io/tls-acme: "true"
  tls: true